### ISSUE TITLE
Missing Capability Listener Device - 300S 

### ISSUE THREAD

**Issue by stuartp44** [spkesDE/com.spkes.vesync#3]
Thanks for creating this app, it is apricated! Just wanted to give some feedback regarding a potential bug

When changing the mode on the app. You are unable to change the mode to due to a "Missing Capability Listener: core300sCapability"

I have Homey 2023
Report ID - d86d9902-5c01-45c7-bf4b-df4e19bdf6ba
VeSync App - 0.1.4

![image](https://user-images.githubusercontent.com/1926002/226948717-32f08ec5-13c0-4645-a833-6abcddd5b64e.jpeg)

**Comment by spkesDE** [comment]
Please try the latest test version

https://homey.app/a/com.spkes.vesync/test/

**Comment by spkesDE** [comment]
You may have to re-add the devices

**Comment by stuartp44** [comment]
I can confirm on the test app it works perfectly!

**Comment by spkesDE** [comment]
Awesome! I close this issue now.
